# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copied and adapted from
# https://gist.github.com/lmolkova/09ba0de7f68280f1eac27a6acfd9b1a6?permalink_comment_id=5578799#gistcomment-5578799

from enum import Enum
from typing import Annotated, Any, List, Literal, Union

from pydantic import Base64Encoder, BaseModel, EncodedBytes, Field, RootModel


class Base64OneWayEncoder(Base64Encoder):
    @classmethod
    def decode(cls, data: bytes) -> bytes:
        """NoOp"""
        return data


Base64EncodedBytes = Annotated[
    bytes, EncodedBytes(encoder=Base64OneWayEncoder)
]


class TextPart(BaseModel):
    """
    Represents text content sent to or received from the model.
    """

    type: Literal["text"] = Field(
        description="The type of the content captured in this part.",
        default="text",
    )
    content: str = Field(
        description="Text content sent to or received from the model."
    )

    class Config:
        extra = "allow"


class ToolCallPart(BaseModel):
    """
    Represents a tool call requested by the model.
    """

    type: Literal["tool_call"] = Field(
        description="The type of the content captured in this part.",
        default="tool_call",
    )
    id: str = Field(description="Unique identifier for the tool call.")
    name: str = Field(description="Name of the tool.")
    arguments: Any = Field(
        description="Arguments for the tool call.", default=None
    )

    class Config:
        extra = "allow"


class ToolCallResponsePart(BaseModel):
    """
    Represents a tool call result sent to the model.
    """

    type: Literal["tool_call_response"] = Field(
        description="The type of the content captured in this part.",
        default="tool_call_response",
    )
    id: str = Field(description="Unique tool call identifier.")
    result: Any = Field(description="Tool call result.")

    class Config:
        extra = "allow"


MessagePart = Annotated[
    Union[
        TextPart,
        ToolCallPart,
        ToolCallResponsePart,
        # Add other message part types here as needed,
        # e.g. image URL, image blob, audio URL, structured output, hosted tool call, etc.
        # I added
        "FileDataPart",
        "BlobPart",
    ],
    Field(discriminator="type"),
]


class Role(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class ChatMessage(BaseModel):
    role: Union[Role, str] = Field(
        description="Role of the entity that created the message."
    )
    parts: List[MessagePart] = Field(
        description="List of message parts that make up the message content."
    )

    class Config:
        extra = "allow"


class BlobPart(BaseModel):
    type: Literal["blob"] = "blob"
    mime_type: str
    data: Base64EncodedBytes

    class Config:
        extra = "allow"


class FileDataPart(BaseModel):
    type: Literal["file_data"] = "file_data"
    mime_type: str
    file_uri: str

    class Config:
        extra = "allow"


class InputMessages(RootModel[List[ChatMessage]]):
    """
    Represents the list of input messages sent to the model.
    """

    pass


class FinishReason(str, Enum):
    """
    Represents the reason for finishing the generation.
    """

    STOP = "stop"
    LENGTH = "length"
    CONTENT_FILTER = "content_filter"
    TOOL_CALL = "tool_call"
    ERROR = "error"


class OutputMessage(ChatMessage):
    """
    Represents an output message generated by the model.
    """

    finish_reason: Union[FinishReason, str] = Field(
        description="Reason for finishing the generation."
    )


class OutputMessages(RootModel[List[OutputMessage]]):
    """
    Represents the list of output messages generated by the model.
    """

    pass
